### ISSUE TITLE
🎨 디자인 시스템

### ISSUE THREAD

**Issue by moondev03** [MJU-SW-Contest-2024/Nabi-Android#1]
## 💼 작업 설명

디자인 시스템 작업

<br>

## ✅ To-do

- [x] 폰트 파일 추가 및 폰트 스타일 정의
- [x] 이미지 및 아이콘 에셋 추가
- [x] 디자인 시스템 미리보기 화면 작성

<br>

## ☁️ Reference

<br>
