### ISSUE TITLE
🖋️ 일기 작성 - 날짜 선택 페이지 | 디자인 변경

### ISSUE THREAD

**Issue by moondev03** [MJU-SW-Contest-2024/Nabi-Android#13]
## 💼 작업 설명

일기 작성 플로우 중 날자 선택 페이지의 디자인 및 기획 변경에 따른 코드 수정

<br>

## ✅ To-do

- [x] 커스텀 캘린더 디자인 수정
- [x] 일기 작성 완료된 일자 표시
- [x] 일기 작성 불가한 일자 표시 (미래)
<br>

## ☁️ Reference

<br>
