### ISSUE TITLE
📩 FCM 세팅 및 API 연결

### ISSUE THREAD

**Issue by moondev03** [MJU-SW-Contest-2024/Nabi-Android#19]
## 💼 작업 설명

<br>

## ✅ To-do

- [x] Firebase Console App 등록
- [x] Firebase Setting
- [x] FCM Service Code 작성
- [x] Registration Token 발급
- [x] Registration Token 저장 API
<br>

## ☁️ Reference

<br>
