### ISSUE TITLE
🖋️ 일기 작성 Calendar 수정

### ISSUE THREAD

**Issue by HamBeomJoon** [MJU-SW-Contest-2024/Nabi-Android#65]
## 💼 작업 설명
🖋️ 일기 작성 Calendar 수정

<br>

## ✅ To-do

- [x] 달력 viewPager로 변경
- [x] 오늘 이후 날짜 회색처리
- [x] 선택 날짜 저장
- [x] 코드 리팩토링
- [x] statusBar 수정
- [x] background 설정
<br>

## ☁️ Reference

<br>
