### ISSUE TITLE
🛠️ SignIn 화면, Home 화면 수정

### ISSUE THREAD

**Issue by HamBeomJoon** [MJU-SW-Contest-2024/Nabi-Android#75]
## 💼 작업 설명
🛠️ SignIn 화면, Home 화면 수정

<br>

## ✅ To-do

- [x] SignIn 화면 수정
- [x] Home 화면 수정
- [x] 네이버 로그인 setting
<br>

## ☁️ Reference

<br>
